/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.visão;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import sistema.modelo.Connection.ConexaoBD;
import sistema.modeloBeans.ModeloTabela;
import sistema.modeloBeans.Veiculos;
import sistema.modeloDAO.VeiculosDAO;
/**
 *
 * @author Mario
 */
public class TelaVeiculos extends javax.swing.JFrame {
    
    Veiculos modelo = new Veiculos();
    VeiculosDAO modVeiDao = new VeiculosDAO();
    ConexaoBD cone = new ConexaoBD();
    int flag = 0;

    /**
     * Creates new form TelaVeiculos
     */
    public TelaVeiculos() {
        initComponents();
         preencherTabela("select * from veiculos order by Id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldChassi = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jComboBoxTipoComb = new javax.swing.JComboBox<>();
        jTextFieldNomePro = new javax.swing.JTextField();
        jTextFieldEndPro = new javax.swing.JTextField();
        jTextFieldBairroPro = new javax.swing.JTextField();
        jTextFieldCidadePro = new javax.swing.JTextField();
        jTextFieldCEPPro = new javax.swing.JTextField();
        jTextFieldRGPro = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldAno = new javax.swing.JTextField();
        jFormattedTextFieldFixo = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de veículos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculos);

        jLabel2.setText("Ano:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Chassi:");

        jLabel5.setText("Placa:");

        jLabel6.setText("Tipo de combustível:");

        jLabel7.setText("Nome do Procedente:");

        jLabel8.setText("Endereço do Procedente:");

        jLabel9.setText("Bairro do Procedente:");

        jLabel10.setText("Cidade do Procedente:");

        jLabel11.setText("CEP do Procedente:");

        jLabel12.setText("CPF do Procedente:");

        jLabel13.setText("RG do Procedente:");

        jLabel14.setText("Telefone fixo do Procedente:");

        jLabel16.setText("Telefone Celular do Procedente:");

        jTextFieldModelo.setEnabled(false);

        jTextFieldChassi.setEnabled(false);

        jTextFieldPlaca.setEnabled(false);

        jComboBoxTipoComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina comum", "Gasolina aditivada", "Gasolina premium", "Gasolina formulada", "Etanol", "Etanol aditivado", "GNV (Gás Natural Veicular)", "Diesel", "Diesel S-10", "Diesel aditivado", "Diesel Premium" }));
        jComboBoxTipoComb.setEnabled(false);

        jTextFieldNomePro.setEnabled(false);

        jTextFieldEndPro.setEnabled(false);

        jTextFieldBairroPro.setEnabled(false);

        jTextFieldCidadePro.setEnabled(false);

        jTextFieldCEPPro.setEnabled(false);

        jTextFieldRGPro.setEnabled(false);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldAno.setEnabled(false);

        try {
            jFormattedTextFieldFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFixo.setEnabled(false);

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setEnabled(false);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setEnabled(false);

        jTextFieldID.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(259, 259, 259)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairroPro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldEndPro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)
                                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(146, 146, 146)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCEPPro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCidadePro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFormattedTextFieldCPF))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldRGPro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldFixo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldBairroPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCidadePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldCEPPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel15))
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxTipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldRGPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextFieldFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldEndPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(821, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if(flag == 1){
        modelo.setAno(Integer.parseInt(jTextFieldAno.getText()));
        modelo.setModelo(jTextFieldModelo.getText());
        modelo.setChassi(jTextFieldChassi.getText());
        modelo.setPlaca(jTextFieldPlaca.getText());
        modelo.setTipo_Comb((String) jComboBoxTipoComb.getSelectedItem());
        modelo.setNome_Procendente(jTextFieldNomePro.getText());
        modelo.setEnd_Procendente(jTextFieldEndPro.getText());
        modelo.setBairro_Procendente(jTextFieldBairroPro.getText());
        modelo.setCidade_Procendente(jTextFieldCidadePro.getText());  
        modelo.setCEP_Procendente(jTextFieldCEPPro.getText());
        modelo.setCPF_Procendente(jFormattedTextFieldCPF.getText());
        modelo.setRG_Procendente(jTextFieldRGPro.getText());
        modelo.setTel_Fixo_Procendente(jFormattedTextFieldFixo.getText());
        modelo.setTel_Cel_Procendente(jFormattedTextFieldCelular.getText());
        
        modVeiDao.salvar(modelo);
        
        
        jTextFieldAno.setText("");
        jTextFieldModelo.setText("");
        jTextFieldChassi.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldNomePro.setText("");
        jTextFieldEndPro.setText("");
        jTextFieldBairroPro.setText("");
        jTextFieldCidadePro.setText("");
        jTextFieldCEPPro.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRGPro.setText("");
        jFormattedTextFieldFixo.setText("");
        jFormattedTextFieldCelular.setText("");
        
        jTextFieldAno.setEnabled(false);
        jTextFieldModelo.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jComboBoxTipoComb.setEnabled(false);
        jTextFieldNomePro.setEnabled(false);
        jTextFieldEndPro.setEnabled(false);
        jTextFieldBairroPro.setEnabled(false);
        jTextFieldCidadePro.setEnabled(false); 
        jTextFieldCEPPro.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jTextFieldRGPro.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(false);   
        jButtonSalvar.setEnabled(false);
        preencherTabela("select * from veiculos order by Id");
        
        }else {
        
        modelo.setId(Integer.parseInt(jTextFieldID.getText()));
        modelo.setAno(Integer.parseInt(jTextFieldAno.getText()));
        modelo.setModelo(jTextFieldModelo.getText());
        modelo.setChassi(jTextFieldChassi.getText());
        modelo.setPlaca(jTextFieldPlaca.getText());
        modelo.setTipo_Comb((String) jComboBoxTipoComb.getSelectedItem());
        modelo.setNome_Procendente(jTextFieldNomePro.getText());
        modelo.setEnd_Procendente(jTextFieldEndPro.getText());
        modelo.setBairro_Procendente(jTextFieldBairroPro.getText());
        modelo.setCidade_Procendente(jTextFieldCidadePro.getText());   
        modelo.setCEP_Procendente(jTextFieldCEPPro.getText());
        modelo.setCPF_Procendente(jFormattedTextFieldCPF.getText());   
        modelo.setRG_Procendente(jTextFieldRGPro.getText());
        modelo.setTel_Fixo_Procendente(jFormattedTextFieldFixo.getText());
        modelo.setTel_Cel_Procendente(jFormattedTextFieldCelular.getText());
        
        modVeiDao.Editar(modelo);
        
        jTextFieldID.setText("");
        jTextFieldAno.setText("");
        jTextFieldModelo.setText("");
        jTextFieldChassi.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldNomePro.setText("");
        jTextFieldEndPro.setText("");
        jTextFieldBairroPro.setText("");
        jTextFieldCidadePro.setText("");
        jTextFieldCEPPro.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRGPro.setText("");        
        jFormattedTextFieldFixo.setText("");
        jFormattedTextFieldCelular.setText("");
       
        jTextFieldAno.setEnabled(false);
        jTextFieldModelo.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jComboBoxTipoComb.setEnabled(false);
        jTextFieldNomePro.setEnabled(false);
        jTextFieldEndPro.setEnabled(false);
        jTextFieldBairroPro.setEnabled(false);
        jTextFieldCidadePro.setEnabled(false);
        jTextFieldCEPPro.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false); 
        jTextFieldRGPro.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false);
        jFormattedTextFieldCelular .setEnabled(false);   
        
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        preencherTabela("select * from veiculos order by Id");
        }
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        
        flag = 1;
        jTextFieldAno.setEnabled(true);
        jTextFieldModelo.setEnabled(true);
        jTextFieldChassi.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jComboBoxTipoComb.setEnabled(true);
        jTextFieldNomePro.setEnabled(true);
        jTextFieldEndPro.setEnabled(true);
        jTextFieldBairroPro.setEnabled(true);
        jTextFieldCidadePro.setEnabled(true); 
        jTextFieldCEPPro.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRGPro.setEnabled(true);
        jFormattedTextFieldFixo.setEnabled(true);
        jFormattedTextFieldCelular.setEnabled(true);   
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldID.setText("");
        jTextFieldAno.setText("");
        jTextFieldModelo.setText("");
        jTextFieldChassi.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldNomePro.setText("");
        jTextFieldEndPro.setText("");
        jTextFieldBairroPro.setText("");
        jTextFieldCidadePro.setText("");
        jTextFieldCEPPro.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRGPro.setText("");        
        jFormattedTextFieldFixo.setText("");
        jFormattedTextFieldCelular.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        jTextFieldAno.setEnabled(!true);
        jTextFieldModelo.setEnabled(!true);
        jTextFieldChassi.setEnabled(!true);
        jTextFieldPlaca.setEnabled(!true);
        jComboBoxTipoComb.setEnabled(!true);
        jTextFieldNomePro.setEnabled(!true);
        jTextFieldEndPro.setEnabled(!true);
        jTextFieldBairroPro.setEnabled(!true);
        jTextFieldCidadePro.setEnabled(!true);
        jTextFieldCEPPro.setEnabled(!true); 
        jFormattedTextFieldCPF.setEnabled(!true);
        jTextFieldRGPro.setEnabled(!true);
        jFormattedTextFieldFixo.setEnabled(!true);
        jFormattedTextFieldCelular.setEnabled(!true); 
        
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldID.setText("");
        jTextFieldAno.setText("");
        jTextFieldModelo.setText("");
        jTextFieldChassi.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldNomePro.setText("");
        jTextFieldEndPro.setText("");
        jTextFieldBairroPro.setText("");
        jTextFieldCidadePro.setText("");
        jTextFieldCEPPro.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRGPro.setText("");        
        jFormattedTextFieldFixo.setText("");
        jFormattedTextFieldCelular.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;
        jTextFieldAno.setEnabled(true);
        jTextFieldModelo.setEnabled(true);
        jTextFieldChassi.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jComboBoxTipoComb.setEnabled(true);
        jTextFieldNomePro.setEnabled(true);
        jTextFieldEndPro.setEnabled(true);
        jTextFieldBairroPro.setEnabled(true);
        jTextFieldCidadePro.setEnabled(true);
        jTextFieldCEPPro.setEnabled(true); 
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRGPro.setEnabled(true);
        jFormattedTextFieldFixo .setEnabled(true);   
        jFormattedTextFieldCelular .setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION){
        
            modelo.setId(Integer.parseInt(jTextFieldID.getText()));
            modVeiDao.Excluir(modelo);
            
        jTextFieldAno.setText("");
        jTextFieldModelo.setText("");
        jTextFieldChassi.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldNomePro.setText("");
        jTextFieldEndPro.setText("");
        jTextFieldBairroPro.setText("");
        jTextFieldCidadePro.setText("");
        jTextFieldCEPPro.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRGPro.setText("");        
        jFormattedTextFieldFixo.setText("");
        jFormattedTextFieldCelular.setText("");
        
        jTextFieldAno.setEnabled(false);
        jTextFieldModelo.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldNomePro.setEnabled(false);
        jTextFieldEndPro.setEnabled(false);
        jTextFieldBairroPro.setEnabled(false);
        jTextFieldCidadePro.setEnabled(false);
        jTextFieldCEPPro.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false); 
        jTextFieldRGPro.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false);
        jFormattedTextFieldCelular .setEnabled(false);   
        
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select * from veiculos order by Id");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculosMouseClicked
        // TODO add your handling code here:
       
        String Ano =""+jTableVeiculos.getValueAt(jTableVeiculos.getSelectedRow(), 1);
        
        cone.conexao();
        cone.executaSql("SELECT *FROM veiculos WHERE Ano='"+Ano+"'");
        
        try {
            cone.rs.first();
            jTextFieldID.setText(String.valueOf(cone.rs.getInt("Id")));
            jTextFieldAno.setText(cone.rs.getString("Ano"));
            jTextFieldModelo.setText(cone.rs.getString("Modelo"));
            jTextFieldChassi.setText(cone.rs.getString("Chassi"));
            jTextFieldPlaca.setText(cone.rs.getString("Placa"));
            jComboBoxTipoComb.setSelectedItem(cone.rs.getString("Tipo_Comb"));
            jTextFieldNomePro.setText(cone.rs.getString("Nome_Procendente"));
            jTextFieldEndPro.setText(cone.rs.getString("End_Procendente"));
            jTextFieldBairroPro.setText(cone.rs.getString("Bairro_Procendente"));
            jTextFieldCidadePro.setText(cone.rs.getString("Cidade_Procendente"));
            jTextFieldCEPPro.setText(cone.rs.getString("CEP_Procendente"));
            jFormattedTextFieldCPF.setText(cone.rs.getString("CPF_Procendente"));
            jTextFieldRGPro.setText(cone.rs.getString("RG_Procendente"));
            jFormattedTextFieldFixo.setText(cone.rs.getString("Tel_Fixo_Procendente"));
            jFormattedTextFieldCelular.setText(cone.rs.getString("Tel_Cel_Procendente"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        cone.desconecta();
        
        
    }//GEN-LAST:event_jTableVeiculosMouseClicked

    public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] colunas =  new String[]{"Id", "Ano", "Modelo", "Chassi", "Placa", "Tipo_Comb", "Nome_Procendente", "End_Procendente", "Bairro_Procendente", "Cidade_Procendente", "CEP_Procendente", "CPF_Procendente", "RG_Procendente", "Tel_Fixo_Procendente", "Tel_Cel_Procendente"};    
        cone.conexao();
        cone.executaSql(Sql);
        try{
            cone.rs.first(); 
            do{
            dados.add(new Object[]{cone.rs.getInt("Id"),cone.rs.getString("Ano"),cone.rs.getString("Modelo"),cone.rs.getString("Chassi"),cone.rs.getString("Placa")
            ,cone.rs.getString("Tipo_Comb"),cone.rs.getString("Nome_Procendente"),cone.rs.getString("End_Procendente"),cone.rs.getString("Bairro_Procendente"),cone.rs.getString("Cidade_Procendente")
            ,cone.rs.getString("CEP_Procendente"),cone.rs.getString("CPF_Procendente"),cone.rs.getString("RG_Procendente"),cone.rs.getString("Tel_Fixo_Procendente"),cone.rs.getString("Tel_Cel_Procendente")});
            }while(cone.rs.next());
        
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList"+ex);
        }
        
        ModeloTabela modeloVei = new ModeloTabela(dados, colunas);
        jTableVeiculos.setModel(modeloVei);
        jTableVeiculos.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableVeiculos.getColumnModel().getColumn(0).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTableVeiculos.getColumnModel().getColumn(1).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTableVeiculos.getColumnModel().getColumn(2).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(3).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(4).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(5).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(6).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(7).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(8).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(9).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(10).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(11).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(12).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(12).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(13).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(13).setResizable(true);
        
        jTableVeiculos.getColumnModel().getColumn(14).setPreferredWidth(80);
        jTableVeiculos.getColumnModel().getColumn(14).setResizable(true);
        
        jTableVeiculos.getTableHeader().setReorderingAllowed(false);
        jTableVeiculos.setAutoResizeMode(jTableVeiculos.AUTO_RESIZE_OFF);
        jTableVeiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        cone.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipoComb;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculos;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldBairroPro;
    private javax.swing.JTextField jTextFieldCEPPro;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldCidadePro;
    private javax.swing.JTextField jTextFieldEndPro;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNomePro;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldRGPro;
    // End of variables declaration//GEN-END:variables
}
