/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.visão;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import sistema.modelo.Connection.ConexaoBD;
import sistema.modeloDAO.ClientesDAO;
import sistema.modeloBeans.Clientes;
import sistema.modeloBeans.ModeloTabela;

/**
 *
 * @author Mario
 */
public class TelaClientes extends javax.swing.JFrame {
    
    Clientes modelo = new Clientes();
    ClientesDAO modDao = new ClientesDAO();
    ConexaoBD cone = new ConexaoBD();
    int flag = 0;

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
        preencherTabela("select * from clientes order by Nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldEnd = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCustoCompra = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButtonPesquisa = new javax.swing.JButton();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFixo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextFieldDataCompra = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("RG:");

        jLabel6.setText("Endereço:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Cidade:");

        jLabel13.setText("Custo da compra:");

        jLabel11.setText("Email:");

        jLabel10.setText("Fixo:");

        jLabel9.setText("Celular:");

        jLabel14.setText("CEP:");

        jTextFieldNome.setEnabled(false);

        jTextFieldRG.setEnabled(false);

        jTextFieldEnd.setEnabled(false);

        jTextFieldBairro.setEnabled(false);

        jTextFieldCidade.setEnabled(false);

        jTextFieldCEP.setEnabled(false);

        jTextFieldEmail.setEnabled(false);

        jTextFieldCustoCompra.setEnabled(false);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Buscar por nome:");

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setEnabled(false);

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCel.setEnabled(false);

        try {
            jFormattedTextFieldFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFixo.setEnabled(false);

        jLabel18.setText("Nascimento:");

        try {
            jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNasc.setEnabled(false);

        jLabel19.setText("Data da compra:");

        try {
            jFormattedTextFieldDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataCompra.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ID:");

        jTextFieldID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel11))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jFormattedTextFieldFixo)
                                                                .addGap(29, 29, 29))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jFormattedTextFieldCel)
                                                        .addGap(29, 29, 29)))
                                                .addGap(0, 70, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCustoCompra)))
                                        .addGap(129, 129, 129))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(93, 93, 93)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5))
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jFormattedTextFieldFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldCustoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jFormattedTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButtonPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(819, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        
       if(flag == 1){
        modelo.setNome(jTextFieldNome.getText());
        modelo.setCPF(jFormattedTextFieldCPF.getText());
        modelo.setRG(jTextFieldRG.getText());
        modelo.setEndereço(jTextFieldEnd.getText());
        modelo.setBairro(jTextFieldBairro.getText());
        modelo.setCidade(jTextFieldCidade.getText());
        modelo.setNascimento(jFormattedTextFieldNasc.getText());
        modelo.setCEP(jTextFieldCEP.getText());
        modelo.setTel_Celular(jFormattedTextFieldCel.getText());  
        modelo.setTel_Fixo(jFormattedTextFieldFixo.getText());
        modelo.setEmail(jTextFieldEmail.getText());
        modelo.setCusto_Compra(jTextFieldCustoCompra.getText());
        modelo.setData_Compra(jFormattedTextFieldDataCompra.getText());
      
        modDao.salvar(modelo);
        
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldEnd.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldNasc.setText("");
        jTextFieldCEP.setText("");
        jFormattedTextFieldCel.setText("");
        jFormattedTextFieldFixo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCustoCompra.setText("");        
        jFormattedTextFieldDataCompra.setText("");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldEnd.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false); 
        jTextFieldEmail.setEnabled(false);
        jTextFieldCustoCompra.setEnabled(false);
        jFormattedTextFieldDataCompra .setEnabled(false);   
        
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
         preencherTabela("select * from clientes order by Nome");
       }
       
       else {
        modelo.setId(Integer.parseInt(jTextFieldID.getText()));
        modelo.setNome(jTextFieldNome.getText());
        modelo.setCPF(jFormattedTextFieldCPF.getText());
        modelo.setRG(jTextFieldRG.getText());
        modelo.setEndereço(jTextFieldEnd.getText());
        modelo.setBairro(jTextFieldBairro.getText());
        modelo.setCidade(jTextFieldCidade.getText());
        modelo.setNascimento(jFormattedTextFieldNasc.getText());
        modelo.setCEP(jTextFieldCEP.getText());
        modelo.setTel_Celular(jFormattedTextFieldCel.getText());  
        modelo.setTel_Fixo(jFormattedTextFieldFixo.getText());
        modelo.setEmail(jTextFieldEmail.getText());
        modelo.setCusto_Compra(jTextFieldCustoCompra.getText());   
        modelo.setData_Compra(jFormattedTextFieldDataCompra.getText());
        
        modDao.Editar(modelo);
        
        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldEnd.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldNasc.setText("");
        jTextFieldCEP.setText("");
        jFormattedTextFieldCel.setText("");
        jFormattedTextFieldFixo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCustoCompra.setText("");        
        jFormattedTextFieldDataCompra.setText("");
        jTextFieldPesquisa.setText("");
       
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldEnd.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false); 
        jTextFieldEmail.setEnabled(false);
        jTextFieldCustoCompra.setEnabled(false);
        jFormattedTextFieldDataCompra .setEnabled(false);   
        
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
         preencherTabela("select * from clientes order by Nome");
       }
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        
        flag = 1;
        
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldEnd.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jFormattedTextFieldFixo.setEnabled(true); 
        jTextFieldEmail.setEnabled(true);
        jTextFieldCustoCompra.setEnabled(true); 
        jFormattedTextFieldDataCompra .setEnabled(true);       
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        
        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldEnd.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldNasc.setText("");
        jTextFieldCEP.setText("");
        jFormattedTextFieldCel.setText("");
        jFormattedTextFieldFixo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCustoCompra.setText("");        
        jFormattedTextFieldDataCompra.setText("");
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisa.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // TODO add your handling code here:
        
        modelo.setPesquisa(jTextFieldPesquisa.getText());
        
        Clientes model = modDao.BuscaCliente(modelo);
        jTextFieldNome.setText(model.getNome());
        jTextFieldID.setText(String.valueOf(model.getId()));
        jFormattedTextFieldCPF.setText(model.getCPF());
        jTextFieldRG.setText(model.getRG());
        jTextFieldEnd.setText(model.getEndereço());
        jTextFieldBairro.setText(model.getBairro());
        jTextFieldCidade.setText(model.getCidade());
        jFormattedTextFieldNasc.setText(model.getNascimento());
        jTextFieldCEP.setText(model.getCEP());
        jFormattedTextFieldCel.setText(model.getTel_Celular());
        jFormattedTextFieldFixo.setText(model.getTel_Fixo());
        jTextFieldEmail.setText(model.getEmail());
        jTextFieldCustoCompra.setText(model.getCusto_Compra());
        jFormattedTextFieldDataCompra.setText(model.getData_Compra());
        
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jTextFieldRG.setEnabled(!true);
        jTextFieldEnd.setEnabled(!true);
        jTextFieldBairro.setEnabled(!true);
        jTextFieldCidade.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jTextFieldCEP.setEnabled(!true);
        jFormattedTextFieldCel.setEnabled(!true);
        jFormattedTextFieldFixo.setEnabled(!true); 
        jTextFieldEmail.setEnabled(!true);
        jTextFieldCustoCompra.setEnabled(!true);
        jFormattedTextFieldDataCompra .setEnabled(!true);       
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisa.setEnabled(true);
         jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldEnd.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldNasc.setText("");
        jTextFieldCEP.setText("");
        jFormattedTextFieldCel.setText("");
        jFormattedTextFieldFixo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCustoCompra.setText("");        
        jFormattedTextFieldDataCompra.setText("");
        jTextFieldPesquisa.setText("");
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        
        flag = 2;
        
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldEnd.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jFormattedTextFieldFixo.setEnabled(true); 
        jTextFieldEmail.setEnabled(true);
        jTextFieldCustoCompra.setEnabled(true);
        jFormattedTextFieldDataCompra .setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION){
        
            modelo.setId(Integer.parseInt(jTextFieldID.getText()));
            modDao.Excluir(modelo);
            
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldEnd.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldNasc.setText("");
        jTextFieldCEP.setText("");
        jFormattedTextFieldCel.setText("");
        jFormattedTextFieldFixo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCustoCompra.setText("");        
        jFormattedTextFieldDataCompra.setText("");
        jTextFieldPesquisa.setText("");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldEnd.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jFormattedTextFieldFixo.setEnabled(false); 
        jTextFieldEmail.setEnabled(false);
        jTextFieldCustoCompra.setEnabled(false);
        jFormattedTextFieldDataCompra .setEnabled(false);   
        
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
         preencherTabela("select * from clientes order by Nome");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
         String Nome =""+jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1);
        cone.conexao();
        cone.executaSql("SELECT *FROM clientes WHERE Nome='"+Nome+"'");
        
        try {
            cone.rs.first();
            jTextFieldID.setText(String.valueOf(cone.rs.getInt("Id")));
            jTextFieldNome.setText(cone.rs.getString("Nome"));
            jFormattedTextFieldCPF.setText(cone.rs.getString("CPF"));
            jTextFieldRG.setText(cone.rs.getString("RG"));
            jTextFieldEnd.setText(cone.rs.getString("Endereço"));
            jTextFieldBairro.setText(cone.rs.getString("Bairro"));
            jTextFieldCidade.setText(cone.rs.getString("Cidade"));
            jFormattedTextFieldNasc.setText(cone.rs.getString("Nascimento"));
            jTextFieldCEP.setText(cone.rs.getString("CEP"));
            jFormattedTextFieldCel.setText(cone.rs.getString("Tel_Celular"));
            jFormattedTextFieldFixo.setText(cone.rs.getString("Tel_Fixo"));
            jTextFieldEmail.setText(cone.rs.getString("Email"));
            jTextFieldCustoCompra.setText(cone.rs.getString("Custo_Compra"));
            jFormattedTextFieldDataCompra.setText(cone.rs.getString("Data_Compra"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }
            cone.desconecta();
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        
        
    }//GEN-LAST:event_jTableClientesMouseClicked

    public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] colunas =  new String[]{"Id", "Nome", "CPF", "RG", "Endereço", "Bairro", "Cidade", "Nascimento", "CEP", "Tel_Celular", "Tel_Fixo", "Email", "Custo_Compra", "Data_Compra"};

        cone.conexao();
        cone.executaSql(Sql);
        
        try{    
            cone.rs.first();
            
            do{
            
                dados.add(new Object[]{cone.rs.getInt("Id"),cone.rs.getString("Nome"),cone.rs.getString("CPF"),
                    cone.rs.getString("RG"),cone.rs.getString("Endereço"),cone.rs.getString("Bairro"),cone.rs.getString("Cidade"),cone.rs.getString("Nascimento"),
                    cone.rs.getString("CEP"),cone.rs.getString("Tel_Celular"),cone.rs.getString("Tel_Fixo"),cone.rs.getString("Email"),cone.rs.getString("Custo_Compra"),cone.rs.getString("Data_Compra")});
            }while(cone.rs.next());
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro ao preencher lista"+ex);
        
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableClientes.setModel(modelo);
        jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(23);
        jTableClientes.getColumnModel().getColumn(0).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableClientes.getColumnModel().getColumn(1).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(2).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(3).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(4).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(5).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(6).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(7).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(8).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(9).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(10).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(11).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(12).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(12).setResizable(true);
        
        jTableClientes.getColumnModel().getColumn(13).setPreferredWidth(80);
        jTableClientes.getColumnModel().getColumn(13).setResizable(true);
       
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jTableClientes.setAutoResizeMode(jTableClientes.AUTO_RESIZE_OFF);
        jTableClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
        cone.desconecta();
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCompra;
    private javax.swing.JFormattedTextField jFormattedTextFieldFixo;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCustoCompra;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnd;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables
}
